### ISSUE TITLE
API Workshop: Sep 11-12, 2023

### ISSUE THREAD

**Issue by RinatS** [im-customers/first-american#3]
Add the contact info below:

- First Name/Last Name
- Business email address
- Role in customer org

**Comment by snahamedfai** [comment]
Shaik Ahamed

**Comment by RinatS** [comment]
Rinat Shagisultanov
Tech Director
rinat.shagisultanov@infomagnus.com

**Comment by jet4423** [comment]
John Trump
jtrump@firstam.com
devops engineer

**Comment by dywilson-firstam** [comment]
- Dylan Wilson
- dywilson@firstam.com
- Lead DevOps Engineer

**Comment by cbilsland** [comment]
Chris Bilsland
IT Manager (ARPS Operations)
cbilsland@firstam.com

**Comment by MithraVarma** [comment]
Nagendra Bhupathiraju
nbhupathiraju@firstam.com
DevOps Eng

**Comment by raghuram1220** [comment]
Raghuram vejendla
rvejendla@firstam.com
DevOps Eng.

**Comment by ssiddiqui65** [comment]
Shahid Siddiqui
ssiddiqui@firstam.com
Devops Eng

**Comment by RinatS** [comment]
Recording 1: [link](https://infomagnus365-my.sharepoint.com/:v:/g/personal/rinat_shagisultanov_infomagnus_com/EXNbXqWmxghHln_zP9fQWA4BInL9Xm2WAAEENoRaHqwcEQ?e=BgKaWV)
Recording 2: [link](https://infomagnus365-my.sharepoint.com/:v:/g/personal/rinat_shagisultanov_infomagnus_com/EReLP9BhnPlMsHRYzJPgRnsBSFKERaKBlrNTgZl6KXjrww?e=xM8VHV)
